# -*- coding: utf-8 -*-
"""
Created on Thu Apr 30 20:18:39 2020

@author: Dell
"""

import smtplib 
import requests 
from bs4 import BeautifulSoup 

companies={'ITC':"less 15","GODFRYPHLP":"more 10"}
message="hey, this is an automated mail generated by dhiraj tatavarthi on alert tiggers on your stocks"

def get_pe(company,trigger):
    if(1):
        URL = "https://www.screener.in/company/ITC/"
        r = requests.get(URL) 
        
          
        soup = BeautifulSoup(r.content, 'html.parser') 
        table=soup.find(id='profit-loss') 
        data_all=table.find_all(class_='responsive-holder')
        
        
        
        # P/E
        sect_all=soup.find('section') 
        four_colm=sect_all.find_all(class_="four columns")
        pe=four_colm[4]
        value=pe.find('b')
        v=value.get_text()
        
        side,trig=trigger.split()
        trig=float(trig)
        
        if(side=='less' and trig>float(v)):
            return(" \n "+company+" P/E is less than "+str(trig)+" with a current value of "+str(v))
        elif(side=='more' and trig<float(v)):
            return(" \n "+company+" P/E is more than "+str(trig)+" with a current value of "+str(v))
        else:
            return(" ")
        
    

all_comp=list(companies.keys())
alltrig=list(companies.values())
for i in range(len(all_comp)):
    message=message+"\n"+get_pe(all_comp[i],alltrig[i])


'''
mail genration module
'''
  
# creates SMTP session 
s = smtplib.SMTP('smtp.gmail.com', 587) 
  
# start TLS for security 
s.starttls() 
  
# Authentication 
s.login("t.dhiraj1999@gmail.com", "sirisha@2") 
  
# message to be sent 

  
# sending the mail 
s.sendmail("t.dhiraj1999@gmail.com", "kishan_1978@yahoo.com", message) 
  
# terminating the session 
s.quit() 